# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11mGAcizB7RvteBT_BnaC_JrPwCtjXq3b
"""

import math

def add(x, y):
    return x + y

def subtract(x,y):
  return x - y

def divide(x,y):
  if y == 0:
        print("Invalid value for denominator, cant't divide by 0!")
        return None
  return  x / y

def multiply(x,y):
  return x*y

def square(x):
  return x*x

def power(x,y):
  return pow(x, y)

def sqrt(x):
  return math.sqrt(x)

add(5,4)

divide(5,0)

divide(4,2)

multiply(2,2)

square(2)

power(6,6)

sqrt(16)